//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDayWishMail.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailParameters", Namespace="http://schemas.datacontract.org/2004/07/TNMailGateway")]
    [System.SerializableAttribute()]
    public partial class MailParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, byte[]> MailAttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailBccField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailBodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailCcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] MailFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailFileNameField;
        
        private string MailFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailSubjectField;
        
        private string MailToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, byte[]> MailAttachments {
            get {
                return this.MailAttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.MailAttachmentsField, value) != true)) {
                    this.MailAttachmentsField = value;
                    this.RaisePropertyChanged("MailAttachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailBcc {
            get {
                return this.MailBccField;
            }
            set {
                if ((object.ReferenceEquals(this.MailBccField, value) != true)) {
                    this.MailBccField = value;
                    this.RaisePropertyChanged("MailBcc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailBody {
            get {
                return this.MailBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.MailBodyField, value) != true)) {
                    this.MailBodyField = value;
                    this.RaisePropertyChanged("MailBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailCc {
            get {
                return this.MailCcField;
            }
            set {
                if ((object.ReferenceEquals(this.MailCcField, value) != true)) {
                    this.MailCcField = value;
                    this.RaisePropertyChanged("MailCc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] MailFile {
            get {
                return this.MailFileField;
            }
            set {
                if ((object.ReferenceEquals(this.MailFileField, value) != true)) {
                    this.MailFileField = value;
                    this.RaisePropertyChanged("MailFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailFileName {
            get {
                return this.MailFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MailFileNameField, value) != true)) {
                    this.MailFileNameField = value;
                    this.RaisePropertyChanged("MailFileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MailFrom {
            get {
                return this.MailFromField;
            }
            set {
                if ((object.ReferenceEquals(this.MailFromField, value) != true)) {
                    this.MailFromField = value;
                    this.RaisePropertyChanged("MailFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailSubject {
            get {
                return this.MailSubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.MailSubjectField, value) != true)) {
                    this.MailSubjectField = value;
                    this.RaisePropertyChanged("MailSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MailTo {
            get {
                return this.MailToField;
            }
            set {
                if ((object.ReferenceEquals(this.MailToField, value) != true)) {
                    this.MailToField = value;
                    this.RaisePropertyChanged("MailTo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/TNMailGateway")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sendMail", ReplyAction="http://tempuri.org/IService1/sendMailResponse")]
        void sendMail(BDayWishMail.ServiceReference.MailParameters objMail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sendMail", ReplyAction="http://tempuri.org/IService1/sendMailResponse")]
        System.Threading.Tasks.Task sendMailAsync(BDayWishMail.ServiceReference.MailParameters objMail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        BDayWishMail.ServiceReference.CompositeType GetDataUsingDataContract(BDayWishMail.ServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<BDayWishMail.ServiceReference.CompositeType> GetDataUsingDataContractAsync(BDayWishMail.ServiceReference.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : BDayWishMail.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<BDayWishMail.ServiceReference.IService1>, BDayWishMail.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void sendMail(BDayWishMail.ServiceReference.MailParameters objMail) {
            base.Channel.sendMail(objMail);
        }
        
        public System.Threading.Tasks.Task sendMailAsync(BDayWishMail.ServiceReference.MailParameters objMail) {
            return base.Channel.sendMailAsync(objMail);
        }
        
        public BDayWishMail.ServiceReference.CompositeType GetDataUsingDataContract(BDayWishMail.ServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<BDayWishMail.ServiceReference.CompositeType> GetDataUsingDataContractAsync(BDayWishMail.ServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
